package opta.optaprj;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Computer implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Computer() {
    }

}